#!/usr/bin/env python
# coding: utf-8

# In[ ]:


!pip install uv && uv pip install sovai['full'] --system > output.log 2>&1

# In[1]:


import sovai as sov

sov.token_auth(token="visit https://sov.ai/profile for your token")

# Load ratios - takes around 5 mins to load data 
df_mega = sov.data("accounting/weekly", start_date="2021-01-26").select_stocks("mega")

# In[2]:


df_mega.head()

# This looks at all of the data for every ticker to calculate the features. The `extract_features` module generates a diverse set of features that can be categorized based on the nature of the calculations.
# 
# The type of features generated by the feature_extractor module include:
# 
#     Statistical Features
#     Entropy and Complexity Features
#     Frequency and Streak Features
#     Energy and Magnitude Features
#     Statistical and Distributional Features
#     Position Features

# In[ ]:


# Example 1: Default parameters (lookback=None, features=None, every="all")
result1 = df_mega.extract_features(every="all"); result1.head()

# In[22]:


# Example 2: Here we specify a lookback period, and how oftern we want the calculation to run
result2 = df_mega.extract_features(lookback=12,every='week'); result2.head()

# In[24]:


# Example 3: Custom feature list for extraction
result3 = df_mega.extract_features(lookback=12,every='week', features=["operating_working_capital","cash_short_term"]); result3.head()


# In[26]:


# Example 4: Using monthly rolling features with a lookback period of 2 months
result4 = df_mega.extract_features(lookback='2mo', every='month'); result4.head()
